### ISSUE TITLE
Missing informations

### ISSUE THREAD

**Issue by MaKaNu** [Mgancita/cookiecutter-pypackage#16]
I tried first the originial pypackage template for cookiecutters and was disapointed about the usage with travis ci. So I searched for a template with github actions instead and found yours. I think I like most of the added Features but need to inform about a few of them. Specific poetry and the usage is something I need to learn if I want to use this template. It would be nice to have a updated version of the README to have a better understanding or at least a good starting point to reproduce the intendance of the template.

**Comment by Mgancita** [comment]
Hi!

I'm glad you decided to try the cookiecutter! Have you looked at the "Getting Started" section of the [docs](https://mgancita.github.io/cookiecutter-pypackage/)? This will give you the walkthrough of setting up the cookiecutter. As for more info on Poetry I'd visit their [official docs](https://python-poetry.org/docs/) as they do a great job so I wouldn't be able to explain it any better.

**Comment by MaKaNu** [comment]
Sorry for late response. Sadly I am very busy at the moment and I was not able to look inside. But I did a short look inside. What I was seeing on the first glance was the thing I actually was looking for. So the missing Information in the Readme is a link to this documentation. So I thought Contributing it is ;)

**Comment by Mgancita** [comment]
Oh didn't even realize that was missing on the readme! Just merged in your PR. Thanks for the first external pull request!

**Comment by MaKaNu** [comment]
It was a plessure!
