### ISSUE TITLE
Working API Key for Test PyPI

### ISSUE THREAD

**Issue by MaKaNu** [Mgancita/cookiecutter-pypackage#18]
You mentioned in the documentation, that you had issues with an API Key for Test PyPI. I just followed the information you have written down until the point where you wrote to enter username and password for the PyPI account. As I created an API Key for my Account I realized the information to use the API key. Their [Website][1] quotes: 

- set username to `__token__`
- set password to the token with the prefix `pypi-`

So instead of using username and password as you mentioned I used the token as described. And what should I say it worked. If you might confirm my success for any of your packages, we could change the documentation.

**Comment by Mgancita** [comment]
oh that's awesome! Thanks for figuring that out! 

I'll try that for one of my packages this weekend to confirm and then we can move forward!

**Comment by Mgancita** [comment]
Had some issues with the repo and accidentally committed the changes w/o a PR. The update is [here](https://github.com/Mgancita/cookiecutter-pypackage/commit/cf531a5173da640f64017941d8345817a3682a75) @MaKaNu  if you want to check it out and lmk if it works for you

**Comment by MaKaNu** [comment]
As I mentioned in the PR review: It worked for me.
